### ISSUE TITLE
Uncaught TypeError: trim() expects parameter 1 to be string, bool given in /app/updater.php:12

### ISSUE THREAD

**Issue by drevel123** [b2un0/docker-netcup-dyndns#2]
Updating the IPv4 doesn't work, for some reason the url 'https://v4.ident.me' returns 'false' when using the script via docker. Opening the url in the webbrowser returns my IPv4 as intended. The same goes for IPv6 (the error is in line 18 then). Somehow, every now and then it works without throwing errors.

`today at 20:46:45`
`today at 20:46:45 Warning: file_get_contents(): php_network_getaddresses: getaddrinfo failed: Name does not resolve in /app/updater.php on line 12`
`today at 20:46:45`
`today at 20:46:45 Warning: file_get_contents(https://v4.ident.me): failed to open stream: php_network_getaddresses: getaddrinfo failed: Name does not resolve in /app/updater.php on line 12`
`today at 20:46:45`
`today at 20:46:45 Fatal error: Uncaught TypeError: trim() expects parameter 1 to be string, bool given in /app/updater.php:12`
`today at 20:46:45 Stack trace:`
`today at 20:46:45 #0 /app/updater.php(12): trim(false)`
`today at 20:46:45 #1 {main}`
`today at 20:46:45   thrown in /app/updater.php on line 12`

**Comment by bench-marc** [comment]
I have the same issue.
Somehow the container has no access to the internet.
Might be a problem with DNS.

**Comment by bench-marc** [comment]
I fixed the issue for me by updating libseccomp on my host (raspberry pi) as described in this post:
https://github.com/alpinelinux/docker-alpine/issues/135#issuecomment-816603722
