### ISSUE TITLE
Feature Request: Show timestamps in logs

### ISSUE THREAD

**Issue by Daniel-Kalus** [b2un0/docker-netcup-dyndns#3]
Hey, wonderful container you have here, I've been using it for some time now. It would be cool if the docker logs started with the timestamp on each line, so instead of 

```
api login successful 
dns recordset NOT updated (no changes) 
api logout successful
```

it would look like:

```
[2022-07-10 18:14:20] api login successful 
[2022-07-10 18:14:21] dns recordset NOT updated (no changes) 
[2022-07-10 18:14:22] api logout successful
```

That way you could see when and how often your internet provider assigns your router a new IP address.

**Comment by b2un0** [comment]
the docker logs have builtin timestamps

`docker logs --timestamps`

https://docs.docker.com/engine/reference/commandline/logs/

**Comment by Daniel-Kalus** [comment]
Thanks, I didn't know that!
