### ISSUE TITLE
Error in line 2 of updater.php

### ISSUE THREAD

**Issue by scrapix** [b2un0/docker-netcup-dyndns#4]
Hey @b2un0, thank you for your great work. 
I'm getting an error, thus the ip update does not work.
Maybe you can help?

`startup /entrypoint.sh
configure cron: */10 * * * * php /app/updater.php
run: /usr/sbin/crond -f
Warning: file_get_contents(http://v4.ident.me): Failed to open stream: Connection refused in /app/updater.php on line 12
Fatal error: Uncaught TypeError: trim(): Argument #1 ($string) must be of type string, bool given in /app/updater.php:12

Stack trace:
#0 /app/updater.php(12): trim(false)`

**Comment by b2un0** [comment]
it looks like your container doen't have network.

can you please try to open `http://v4.ident.me` in your browser?
